version: "3.9"
services: 
  frontend:
    container_name: portfolio
    image: portfolio
    build:
      context: .
      target: development
    volumes: 
      - .:/usr/local/src
    ports:
      - 3000:3000
    command: yarn dev